### ISSUE TITLE
Convert practicalplants.json to JS file

### ISSUE THREAD

**Issue by petteripitkanen** [Ecohackerfarm/powerplant#70]
Currently `practicalplants.json` is in mongoexport JSON format, we don't use MongoDB anymore so it would be better to convert this to plain JS file that can be included with `require`.

**Comment by gljivar** [comment]
What is the general process of regenerating practicalplants.json file? Do you do regular updates to have file synced periodically with practicalplants.org?

Maybe it would be good to instead of converting current file, create functions for retrieving data from practicalplants.org directly to plain JS file (e.g. sync with practicalplants).

**Comment by petteripitkanen** [comment]
practicalplants.org is one input (currently the only) for creating the internal powerplant `Crop` objects. The purpose of having this dataset in the repo is to be able to quickly set up local environment for testing the app, and on the other hand it is for testing the companionship algorithm and the search and filtering functions with real data.

Originally `practicalplants.json` was generated once with [mediawiki_scraper](https://github.com/lovelaced/mediawiki_scraper). I am not sure if it makes sense to regenerate this static file with new data, at least not often.

There have been ideas to automatically (or maybe semi-automatically with admin input queue) sync the powerplant server database with practicalplants.org. However practicalplants.org seems not to be updated or maintained by anyone for years.

But this issue is simply for converting `practicalplants.json` to a format that is easier to use and easier to be exported to other projects.
