### ISSUE TITLE
Clients should eliminate duplicate Crops coming from server

### ISSUE THREAD

**Issue by petteripitkanen** [Ecohackerfarm/powerplant#73]
Currently when the server database is destroyed and created again with `npm run migrate`, the clients end up with duplicate Crop documents (this can be fixed by manually removing the local IndexedDB databases). There should be logic in the client to keep only the latest crop document that comes from the server.

**Comment by petteripitkanen** [comment]
Actually, it is probably better to make the migration process less intrusive so that the object IDs never change, otherwise later when the object graphs get more complex it'll get really complicated for the client to reconstruct them.

**Comment by gljivar** [comment]
Temporarily issue is not visible if incognito mode is used for starting the application locally.
IndexedDb can be deleted by opening Chrome Dev tools, then Application and clear storage.

It would be good to solve this issue, because I just noticed it now when it was raised as an issue, although it was strange to me that there are multiple items with same name.

**Comment by petteripitkanen** [comment]
Yes, the migration process should update the database instead of creating a new one from scratch, but this cannot be done before #67 is resolved.
